language: ruby
sudo: false

cache:
  bundler: true
  directories:
    - /tmp/cache/unicode_conformance
    - /tmp/beanstalkd-1.10

services:
  - memcached
  - redis
  - rabbitmq

addons:
  postgresql: "9.4"

bundler_args: --without test --jobs 3 --retry 3
before_install:
  - "rm ${BUNDLE_GEMFILE}.lock"
  - "gem update bundler"
  - "[ -f /tmp/beanstalkd-1.10/Makefile ] || (curl -L https://github.com/kr/beanstalkd/archive/v1.10.tar.gz | tar xz -C /tmp)"
  - "pushd /tmp/beanstalkd-1.10 && make && (./beanstalkd &); popd"

before_script:
  - bundle update

  # Set Sauce Labs username and access key. Obfuscated, purposefully not encrypted.
  # Decodes to e.g. `export VARIABLE=VALUE`
  - $(base64 --decode <<< "ZXhwb3J0IFNBVUNFX0FDQ0VTU19LRVk9YTAzNTM0M2YtZTkyMi00MGIzLWFhM2MtMDZiM2VhNjM1YzQ4")
  - $(base64 --decode <<< "ZXhwb3J0IFNBVUNFX1VTRVJOQU1FPXJ1YnlvbnJhaWxz")

script: 'ci/travis.rb'

env:
  global:
    - "JRUBY_OPTS='--dev -J-Xmx1024M'"
    - "GEM=ar:mysql2"
    - "TESTOPT='-v --seed=55338'"
  matrix:
    - "N=1"
    - "N=2"
    - "N=3"
    - "N=4"
    - "N=5"
    - "N=6"
    - "N=7"
    - "N=8"
    - "N=9"
    - "N=10"
    - "N=11"
    - "N=12"
    - "N=13"
    - "N=14"
    - "N=15"
    - "N=16"
    - "N=17"
    - "N=18"
    - "N=19"
    - "N=20"

rvm:
  - 2.2.6

matrix:
  fast_finish: true

notifications:
  email: false
